### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by faso**
moive -> movie

### CODE REVIEW

**Comment by faso** [comment]
Boy would I hate to be the author of that merge tool.

**Comment by faso** [comment]
Bump @surveyjsdeveloper

**Comment by faso** [comment]
Bump @mpreyskurantov @andrewtelnov @dmitrykurmanov

**Comment by dmitrykurmanov** [comment]
@faso, hello! Thank you! Sorry for late response. We'll work on new site (one for library, editor and service) and we'll fix the typo.

**Pull request closed without merging**
